version: '3.9'

services:
  sm_assignment:
    image: php_assignment:latest
    container_name: php_assignment
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
    ports:
      - "7777:80"
    volumes:
      - ./tests:/app/tests
      - ./public:/app/public
      - ./module:/app/module

networks:
  default:
    name: sm_assignment

volumes:
  myCodeVolume: